### ISSUE TITLE
Custom group

### ISSUE THREAD

**Issue by zsinx6** [Microdisseny/django-groupadmin-users#4]
Is it possible to use it with custom groups?

For example
```from django.contrib.auth.models import Group

class GroupExtend(models.Model):
    group = models.OneToOneField(Group)
    # other fields```

**Comment by manelclos** [comment]
Hi @zsinx6,

I'd say that it is better that you create your own form like in the code:
https://github.com/Microdisseny/django-groupadmin-users/blob/master/groupadmin_users/forms.py
