### ISSUE TITLE
Big amount of sql queries in GroupAdmin

### ISSUE THREAD

**Issue by wwarne** [Microdisseny/django-groupadmin-users#6]
Hello! 
I use django debug toolbar and I have noticed that then using `GroupAdmin` class in my admin I get 260+ sql queries related with `contenttype` table.

After some digging and investigating I have found that this problem was already fixed in the default admin model for `Groups` - `django.contrib.auth.admin.GroupAdmin` in method `formfield_for_manytomany`

https://github.com/django/django/blob/54d91795408c878ad335226a87a44961d7f646a9/django/contrib/auth/admin.py#L31

This is a commit with fix in django:
https://github.com/django/django/commit/283526a5a6854d1ba43f2b277d43cdd2b7f19c54

So probably if you have some time you could inherit from the `GroupAdmin` or just copy those changes.

**Comment by manelclos** [comment]
Hi @wwarne, completely agree. It would be great if you could send a PR and take all the credit for the improvement. The ModelAdmin should inherit from the original `GroupAdmin` as you propose, that would be my first option, I can't say why it is not like that, maybe there was some issue.

**Comment by wwarne** [comment]
@manelclos Cool, i'll do a PR then!
